[default_apps]
terminal = "foot"
browser = "/opt/zen-browser-bin/zen-bin %u"

[units]
lengths = "feet"
weights = "lbs"
volumes = "l"
temperatures = "F"
_currency = "usd"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 800
height = 600
gsk_renderer = "cairo"
icon_paths = ["~/.config/sherlock/icons/"]
icon_size = 22
search_icon = false
use_base_css = true
status_bar = false
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]
use_custom_css = true

[behavior]
cache = "~/.cache/sherlock/sherlock_desktop_cache.json"
caching = true
daemonize = false

[binds]

[files]
config = "~/.config/sherlock/config.toml"
css = "~/.config/sherlock/themes/oxocarbon.css"
fallback = "~/.config/sherlock/fallback.json"
alias = "~/.config/sherlock/sherlock_alias.json"
ignore = "~/.config/sherlock/sherlockignore"
actions = "~/.config/sherlock/sherlock_actions.json"

[pipe]
