#!/bin/sh

bspc monitor eDP -d 1 2 3 4
bspc config border_width 0
bspc config window_gap 9
bspc rule -r '*'
bspc rule -a sun-awt-X11-XDialogPeer state=floating
bspc config focus_follows_pointer true
 feh --bg-fill ~/Pictures/bg.jpg
 sxhkd &
 picom &
 eww open bar -c ~/.config/eww/ &
# eww open desktopIcons -c ~/.config/eww/ &
 bash ~/.config/eww/scripts/notifications.sh
